name: Validate dotnet
on: workflow_dispatch
jobs:
  setup-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet 7.0
        uses: ./
        with:
          dotnet-version: 7.0
